url: 
baseurl: /agency-jekyll-theme/

# Site settings
title: Whista Engineering
email: your-email@domain.com
description: "The best Engineering this side of Byron"


# Team names, titles and social links
people:
- name: J Dubs
  email: jamie@whista.com
  pic: 1
  position: Partner
  social:
    - title: linkedin
      url: #
    - title: envelope
      url: mailto:jamie@wseng.ca

- name: Stallie
  email: a@b.com
  pic: 2
  position: Partner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/adam-stallaert-7073048a/
    - title: envelope
      url: mailto:adam@wseng.ca

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: XXXX 
  - line: Komoka, Ontario N0L 1R0

# Build settings
markdown: kramdown
permalink: pretty