url: 
baseurl: /agency-jekyll-theme/

# Site settings
title: Whitty Stallaert Engineering
email: info@wseng.ca
description: Mechanical, Electrical and Plumbing Engineering Services


# Team names, titles and social links
people:
- name: Jamie Whitty, P.Eng., LEED AP
  pic: jamie
  position: Partner
  social:
    - title: linkedin
      url: #
    - title: envelope
      url: mailto:jamie@wseng.ca

- name: Adam Stallaert, P.Eng.
  pic: adam
  position: Partner
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/adam-stallaert-7073048a/
    - title: envelope
      url: mailto:adam@wseng.ca

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: XXXX 
  - line: Komoka, Ontario N0L 1R0

# Build settings
markdown: kramdown
permalink: pretty